main: manhunt.main.Main
name: Manhunt
version: 0.2.0
api-version: 1.16
description: A recreation of the YouTuber Dream's Minecraft Manhunt plugin
author: Eugene Chau
commands:
  addhunter:
    description: Add a player as a hunter.
    usage: /addhunter <username>
  gethunters:
    description: Get the usernames of all current hunters.
    usage: /gethunters
  removehunter:
    description: Remove a player from the list of hunters.
    usage: /removehunter <username>
  togglenethertracking:
    description: Toggles the ability for hunters to track players in the Nether.
    usage: /togglenethertracking